name: Build (Android)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null
jobs:
  build:
    runs-on:
      - self-hosted
      - macOS
      - ARM64
      - turningflow-macos
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate
        uses: ./.github/actions/generate
        with:
          platform: android
          release: false
      - name: Install JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: "17"
      - name: Finalize Android SDK
        run: |
          /bin/bash -c "yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses > /dev/null"
      - name: Build example for Android
        env:
          JAVA_OPTS: -XX:MaxHeapSize=6g
        run: yarn workspace @unomed/react-native-matrix-sdk-example build:android
    if: ${{ (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository) }}
