name: NPM install
on:
  push:
    branches:
      - main
  workflow_dispatch: null
jobs:
  install:
    runs-on:
      - self-hosted
      - Linux
      - X64
      - turningflow-linux
    steps:
      - name: Install
        run: |
          mkdir my-app
          cd my-app
          npm init -y
          npm install @unomed/react-native-matrix-sdk
