name: Library
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null
jobs:
  build:
    runs-on:
      - self-hosted
      - Linux
      - ARM64
      - turningflow-linux
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JS
        uses: ./.github/actions/setup-js
      - name: Build package
        run: yarn prepare
    if: ${{ (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository) }}
